---
- name: Install weechat
  package: name={{item}} state=present
  with_items:
    - screen
    - weechat
  become: True

- name: create systemd user dir
  file: path=~/.config/systemd/user/ state=directory

- name: Configure weechat systemd service
  copy: src=files/weechat.service dest=~/.config/systemd/user/weechat.service

- name: Set weechat systemd user service
  systemd: name=weechat state=started enabled=yes user=yes daemon_reload=yes

- name: Theme weechat
  shell: creates=~/.weechat/themed echo {{item}} >~/.weechat/weechat_fifo
  with_items:
    - '*/set weechat.bar.status.color_bg 0'
    - '*/set weechat.bar.title.color_bg 0'
    - '*/set weechat.color.chat_nick_colors 1,2,3,4,5,6'
    - '*/set weechat.color.chat_highlight_bg red'
    - '*/set weechat.color.chat_highlight black'
    - '*/bar toggle nicklist'
    - '*/bar toggle title'
    - '*/bar toggle status'
    - '*/set weechat.look.separator_horizontal " "'
    - '*/set weechat.look.prefix_suffix " "'
    - '*/set weechat.bar.buffers.position top'
    - '*/set weechat.bar.input.items "            ,[input_search],[input_paste],input_text"'
    - '*/set weechat.bar.input.color_delim 240'
    - '*/set weechat.look.prefix_error "✘"'
    - '*/set weechat.look.prefix_join ""'
    - '*/set weechat.look.prefix_quit ""'
    - '*/set weechat.look.read_marker none'
    - '*/script install colorize_nicks.py highmon.pl'
    - '*/set env TERM screen-256color'
    - '*/upgrade'
    - '*/set weechat.look.buffer_time_format \${color:252}%H\${color:245}%M\${color:240}%S'

- name: Create themed file
  file: path=~/.weechat/themed state=touch
