---
- name: Install weechat
  package: name={{item}} state=present
  with_items:
    - screen
    - weechat
  become: True

- name: create systemd user dir
  file: path=~/.config/systemd/user/ state=directory

- name: Configure weechat systemd service
  copy: src=files/weechat.service dest=~/.config/systemd/user/weechat.service

- name: Set weechat systemd user service
  systemd: name=weechat state=started enabled=yes user=yes daemon_reload=yes

- name: Theme weechat
  shell: creates=~/.weechat/themed echo {{item}} >~/.weechat/weechat_fifo
  with_items:
    - 'irc.freenode.#weechat */set weechat.bar.status.color_bg 0'
    - 'irc.freenode.#weechat */set weechat.bar.title.color_bg 0'
    - 'irc.freenode.#weechat */set weechat.color.chat_nick_colors 1,2,3,4,5,6'
    - 'irc.freenode.#weechat */set weechat.color.chat_highlight_bg red'
    - 'irc.freenode.#weechat */set weechat.color.chat_highlight black'
    - 'irc.freenode.#weechat */bar toggle nicklist'
    - 'irc.freenode.#weechat */bar toggle title'
    - 'irc.freenode.#weechat */bar toggle status'
    - 'irc.freenode.#weechat */set weechat.look.separator_horizontal " "'
    - 'irc.freenode.#weechat */set buffers.color.hotlist_message_fg 7'
    - 'irc.freenode.#weechat */set buffers.color.current_bg 240'
    - 'irc.freenode.#weechat */set buffers.color.current_fg white'
    - 'irc.freenode.#weechat */set buffers.look.show_number off'
    - 'irc.freenode.#weechat */set weechat.bar.buffers.position top'
    - 'irc.freenode.#weechat */set weechat.look.buffer_time_format ${color:252}%H${color:245}%M${color:240}%S'
    - 'irc.freenode.#weechat */set env TERM screen-256color'
    - 'irc.freenode.#weechat */set weechat.bar.input.items "            ,[input_search],[input_paste],input_text"'
    - 'irc.freenode.#weechat */set weechat.bar.input.color_delim 240'
    - 'irc.freenode.#weechat */set weechat.look.prefix_error "✘"'
    - 'irc.freenode.#weechat */set weechat.look.prefix_join ""'
    - 'irc.freenode.#weechat */set weechat.look.prefix_quit ""'
    - 'irc.freenode.#weechat */set weechat.look.prefix_suffix " "'
    - 'irc.freenode.#weechat */set weechat.look.read_marker none'
    - 'irc.freenode.#weechat */script install colorize_nicks.py highmon.pl'
    - 'irc.freenode.#weechat */upgrade'

- name: Create themed file
  file: path=~/.weechat/themed state=touch
