---
- name: Install Cursors
  aur: name=capitaine-cursors use=trizen

- name: Create .Xresources.d dir
  file: path=~/.Xresources.d state=directory

- name: Configure Cursors
  copy: src=files/cursor dest=~/.Xresources.d/cursor

- name: Init Cursors in .Xresources
  lineinfile: path=~/.Xresources create=yes state=present line='#include ".Xresources.d/cursor"'

