---
- name: Install Cursors
  packer: name=capitaine-cursors state=present

- name: Configure Cursors
  synchronize: src=files/ dest=~/

- name: Init Cursors in .Xresources
  lineinfile: path=~/.Xresources create=yes state=present line='#include ".Xresources.d/cursor"'

