sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t archlinux/dotfiles -f docker/archlinux/Dockerfile .

script:
  - cd dotfiles
  - docker run archlinux/dotfiles ansible-playbook -i docker/archlinux/hosts install.yml
  #- docker run archlinux/dotfiles dotfiles/docker/archlinux/test.sh
