---
- hosts: all

  roles:
    - { role: packages, tags: packages }
    # Server roles
    - { role: zsh, tags: [ 'zsh', 'laptop', 'desktop', 'server' ] }
    - { role: vim, tags: [ 'vim', 'laptop', 'desktop', 'server' ] }
    - { role: terminfo, tags: [ 'terminfo', 'laptop', 'desktop', 'server' ] }
    - { role: screen, tags: [ 'screen', 'laptop', 'desktop', 'server' ] }
    - { role: ssh-agent, tags: [ 'ssh-agent', 'laptop', 'desktop', 'server' ] }
    # Desktop/Laptop roles
    - { role: cursor, tags: [ 'cursor', 'laptop', 'desktop' ] }
    - { role: i3-wm, tags: [ 'i3-wm', 'laptop', 'desktop' ] }
    - { role: compton, tags: [ 'compton', 'laptop', 'desktop' ] }
    - { role: polybar, tags: [ 'polybar', 'laptop', 'desktop' ] }
    - { role: rofi, tags: [ 'rofi', 'laptop', 'desktop' ] }
    - { role: neofetch, tags: [ 'neofetch', 'laptop', 'dekstop' ] }
    - { role: xbindkeys, tags: [ 'xbindkeys', 'laptop' ] }
    - { role: termite, tags: [ 'termite', 'laptop', 'desktop' ] }
    - { role: weechat, tags: [ 'weechat', 'laptop', 'desktop' ] }

  tasks:
    - include_role:
        name: weechat
      when: ansible_env.username == "vagrant"
      tags: [ 'wallpaper', 'desktop' ]
