---
- name: Create img dir
  file:
    path: ~/img
    state: directory

- name: Copy wallpaper
  copy:
    src: wallpaper.jpg
    dest: ~/img/

- name: Init wallpaper in .xprofile
  copy:
    src: wallpaper.sh
    dest: ~/.xprofile.d/
