---
- name: Install compton
  packer: name=compton-git state=present

- name: Configure compton
  synchronize: src=files/ dest=~/

- name: Init compton in .xprofile
  blockinfile:
    path: ~/.xprofile
    create: True
    marker: "### {mark} DOTFILES compton ###"
    content: |
      compton --backend glx --vsync opengl-swc -GCb --config ~/.compton &
