---
- name: install variety
  package:
    name: variety
    state: present
  become: yes

- name: configure variety
  copy:
    src: variety.conf
    dest: ~/.config/variety
    backup: yes

- name: configure variety xprofile
  copy:
    src: variety.sh
    dest: ~/.xprofile.d/
