---
- name: Install Desktop packages
  package: name={{item}} state=present
  with_items:
    - xorg-server
    - xorg-xinit
    - lxappearance
    - slop
    - maim
    - feh
    - xclip
    - xorg-xrdb
    - xorg-xfd
    - connman
    - geary
    - ttf-hack
  become: True

- name: Install Desktop packages (Archlinux)
  packer: name={{item}} state=present
  with_items:
    - google-chrome
    - connman-gtk
    - gnome-ssh-askpass2
    - ttf-font-awesome
    - ttf-unifont
    - ttf-font-icons
  when: ansible_os_family == "Archlinux"
  notify: clean packer tmp

