---
- name: Install common packages
  package: name={{item}} state=present
  with_items:
    - curl
    - wget
  become: True

- name: Include Archlinux packages [if Archlinux]
  include_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"
