---
- name: Install common packages
  package: name={{item}} state=present
  with_items:
    - curl
    - wget
    - pygmentize
  become: True

- import_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"
