[character]
success_symbol = "[➜](purple)"
error_symbol = "[➜](red)"

[directory]
style = "blue"

[cmd_duration]
style = "yellow"
prefix = ""

[git_branch]
symbol = ""
style = "#808080"

[git_status]
style = "red"
prefix = ""
suffix = " "
