[character]
success_symbol = "[➜](purple)"
error_symbol = "[➜](red)"

[directory]
style = "blue"

[cmd_duration]
format = "[$duration](yellow)"

[git_branch]
symbol = ""
style = "#808080"

[git_status]
show_sync_count = true
format = "[$all_status $ahead_behind ](red)"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count}"
