[character]
success_symbol = "[➜](purple)"
error_symbol = "[➜](red)"

[directory]
style = "blue"

[cmd_duration]
format = "[$duration](yellow)"

[git_branch]
symbol = ""
style = "#808080"

[git_status]
style = "red"
show_sync_count = true
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
