---
- name: Create gtk conf dir
  file:
    path: ~/.config/gtk-3.0/
    state: directory

- name: Configure GTK3
  copy:
    src: settings.ini
    dest: ~/.config/gtk-3.0/
    backup: yes

- name: Configure GTK2
  copy:
    src: gtkrc-2.0
    dest: ~/.config/.gtkrc-2.0
    backup: yes

- name: Configure Qt as GTK theme
  copy:
    src: Trolltech.conf
    dest: ~/.config/
    backup: yes

- name: Link Xdefaults
  file:
    src: ~/.Xresources
    dest: ~/.Xdefaults
    state: link
    force: yes

- name: Create .Xresources.d dir
  file:
    path: ~/.Xresources.d
    state: directory
