---
- name: Install termite termcap [FreeBSD]
  # See: https://unix.stackexchange.com/questions/291412/how-can-i-use-terminfo-entries-on-freebsd
  shell: creates=~/.termcap {{item}}
  with_items:
    - 'chmod 755 /usr/share/misc/termcap'
    - 'cat {{ playbook_dir }}/roles/terminfo/files/termite.termcap >> /usr/share/misc/termcap'
    - 'cap_mkdb /usr/share/misc/termcap'
    - 'touch ~/.termcap'
  become: True
  when: ansible_os_family == "FreeBSD"

- name: Install termite terminfo [Archlinux]
  pacman: name=termite-terminfo state=present
  become: True
  when: ansible_os_family == "Archlinux"

- name: Install termite terminfo (Common)
  shell: creates=/root/termite.terminfo {{item}}
  with_items:
    - 'wget "https://github.com/thestinger/termite/blob/master/termite.terminfo" -O /root/termite.terminfo'
    - 'tic -x /root/termite.terminfo'
  become: True
  when: ansible_os_family != "Archlinux" and ansible_os_family != "FreeBSD"
