---
- name: Install polybar
  packer: name={{item}} state=present
  with_items:
    - siji-git
    - polybar-git

- name: Configure polybar
  synchronize: src=files/ dest=~/

- debug:
    msg: "Do not forget to edit MONITOR vars in ~/.config/polybar/launch.sh"

- name: Configure i3lock blur
  lineinfile:
    path: ~/.i3/i3lock-fancy-multimonitor/lock
    regexp: '^BLURTYPE="2x8"'
    line: '#BLURTYPE="2x8"'
  ignore_errors: True

- name: Configure i3lock blur bis
  lineinfile:
    path: ~/.i3/i3lock-fancy-multimonitor/lock
    regexp: '^#BLURTYPE="5x3"'
    line: 'BLURTYPE="5x3"'
  ignore_errors: True
