---
- name: create wofi config dir
  file:
    path: ~/.config/wofi
    state: directory

- name: copy wofi style
  copy:
    src: style.css
    dest: ~/.config/wofi/

- name: copy wofi config
  copy:
    src: config
    dest: ~/.config/wofi/

- name: copy wofi powermenu
  copy:
    src: powermenu.sh
    dest: ~/.config/wofi/
    mode: 0755
