---
- name: Install termite terminfo [Common]
  shell: creates={{ item.creates }} {{ item.cmd }}
  with_items:
    - { creates: '/root/termite.terminfo', cmd: 'wget "https://raw.githubusercontent.com/thestinger/termite/master/termite.terminfo" -O /root/termite.terminfo' }
    - { creates: '/root/.termite.terminfo', cmd: 'tic -x /root/termite.terminfo' }
    - { creates: '/root/.termite.terminfo', cmd: 'touch /root/.termite.terminfo' }
  become: True
