---
- name: install wayland and sway
  pacman:
    name:
      - wayland
      - xorg-server-xwayland
      - sway
      - swaylock
      - waybar
      - grim # screenshots
      - wl-clipboard # clipboard
  become: true

- name: create sway config dir
  file:
    path: ~/.config/sway/
    state: directory

- name: copy configuration file
  template:
    src: config.j2
    dest: ~/.config/sway/config

- name: autostart sway
  copy:
    src: bash_profile
    dest: ~/.bash_profile
