---
- name: install wayland and sway
  pacman:
    name:
      - wayland
      - xorg-server-xwayland
      - sway
      - waybar
      - grim # screenshots
      - slurp # select region
      - wl-clipboard # clipboard
      - playerctl # spotify
  become: true

- name: install aur sway deps
  aur:
    name:
      - swaylock-fancy-git
      - gtk-theme-minwaita #https://github.com/Alexays/Waybar/issues/515

- name: create sway config dir
  file:
    path: ~/.config/sway/
    state: directory

- name: copy configuration file
  template:
    src: sway/config.j2
    dest: ~/.config/sway/config

- name: autostart sway
  copy:
    src: bash_profile
    dest: ~/.bash_profile

- name: copy waybar configuration
  tags: waybar
  synchronize:
    src: waybar
    dest: ~/.config/

- name: create swaylock dir config
  file:
    path: ~/.config/swaylock/
    state: directory

- name: copy swaylock config
  copy:
    src: swaylock.config
    dest: ~/.config/swaylock/config

- name: copy gsettings importer
  copy:
    src: import-gsettings
    dest: ~/.config/sway/
    mode: 0755
