---
- name: install wayland and sway
  pacman:
    name:
      - wayland
      - xorg-server-xwayland
      - sway
      - waybar
      - grim # screenshots
      - wl-clipboard # clipboard
      - playerctl # spotify
      - ttf-font-awesome
  become: true

- name: install aur sway deps
  aur:
    name:
      - swaylock-fancy

- name: create sway config dir
  file:
    path: ~/.config/sway/
    state: directory

- name: copy configuration file
  template:
    src: config.j2
    dest: ~/.config/sway/config

- name: autostart sway
  copy:
    src: bash_profile
    dest: ~/.bash_profile

- name: copy waybar configuration
  synchronize:
    src: waybar
    dest: ~/.config/waybar/
    mode: 0755

- name: create swaylock dir config
  file:
    path: ~/.config/swaylock/
    state: directory

- name: copy swaylock config
  copy:
    src: swaylock.config
    dest: ~/.config/swaylock/config
