---
- name: Install i3-wm
  packer: name={{item}} state=present
  with_items:
    - i3-gaps
    - i3lock

- name: Configure i3-wm
  synchronize: src=files/ dest=~/

- name: Template config file
  template: src=templates/config.j2 dest=~/.i3/config
