---
- name: Install vim
  package: name={{item}} state=present
  with_items:
    - vim
    - powerline
    - powerline-fonts
    - powerline-vim
  become: True

- name: Configure vim
  synchronize: src=files/ dest=~/
