---
- name: Configure ssh-agent
  copy:
    src: ssh-agent.service
    dest: ~/.config/systemd/user/

- name: Configure pam environment
  copy:
    src: pam_environment
    dest: ~/.pam_environment

- name: Start and enable ssh-agent service
  systemd:
    name: ssh-agent
    state: started
    enabled: yes
    scope: user 
