---
- name: SSH-agent as a service
  shell: creates=~/.config/systemd/user/ssh-agent.service stow ssh-agent

- name: Configure ssh-agent as a service
  systemd: name=ssh-agent state=started enabled=yes user=yes daemon_reload=yes

