---
- name: Install neovim
  package:
    name: neovim
    state: present
  become: True

- name: Copy neovim conf file
  copy:
    src: init.vim
    dest: ~/.config/nvim/
  notify: trigger plug install
